# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'UIPickerView_three_level' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  use_frameworks!
  pod 'AFNetworking', '~> 3.1.0'
  pod 'MJExtension', '~> 3.0.13'

  # Pods for UIPickerView_three_level

  target 'UIPickerView_three_levelTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'UIPickerView_three_levelUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
